# -*- coding: utf-8 -*-
"""Firearm_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8E_KwBti8hxpHtESnA84VjDx7VOeXdQ
"""

!apt update
!apt upgrade -y
!uname -m && cat /etc/*release
!gcc --version
!uname -r

ls

# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

!ls -a "/content/drive/My Drive/Colab Notebooks/Firearm/"

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AlexeyAB/darknet/
# %cd darknet/

!apt install libopencv-dev python-opencv ffmpeg

# Commented out IPython magic to ensure Python compatibility.
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
#!sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
# %pycat Makefile

!make

# Commented out IPython magic to ensure Python compatibility.
# %cp cfg/yolov3.cfg cfg/yolo-obj.cfg
!sed -i 's/batch=1/batch=64/g' cfg/yolo-obj.cfg
!sed -i 's/subdivisions=1/subdivisions=32/g' cfg/yolo-obj.cfg
!sed -i 's/classes=80/classes=1/g' cfg/yolo-obj.cfg
!sed -i 's/filters=255/filters=18/g' cfg/yolo-obj.cfg
!sed -i 's/width=416/width=608/g' cfg/yolo-obj.cfg
!sed -i 's/height=416/height=608/g' cfg/yolo-obj.cfg

# Commented out IPython magic to ensure Python compatibility.
# %pycat cfg/yolo-obj.cfg

# Commented out IPython magic to ensure Python compatibility.
all_classes = """Gun
"""

file = """text_file = open("build/darknet/x64/data/obj.names", "w");text_file.write(all_classes);text_file.close()""" 

exec(file)
# %pycat build/darknet/x64/data/obj.names

# Commented out IPython magic to ensure Python compatibility.
obj_data = """classes= 1
train  = build/darknet/x64/data/train.txt
valid  = build/darknet/x64/data/valid.txt
names = build/darknet/x64/data/obj.names
backup = build/darknet/x64/backup/
"""

file = """text_file = open("build/darknet/x64/data/obj.data", "w");text_file.write(obj_data);text_file.close()""" 

exec(file)
# %pycat build/darknet/x64/data/obj.data

# Commented out IPython magic to ensure Python compatibility.
#%mkdir build/darknet/x64/data/obj
# %cp -r "/content/drive/My Drive/Colab Notebooks/Firearm/Gun/." build/darknet/x64/data/obj/
#%cp -r "/content/drive/My Drive/Colab Notebooks/Firearm/Smoking/." build/darknet/x64/data/obj/

ls -1 "/content/drive/My Drive/Colab Notebooks/Firearm/Gun/" | wc -l

# Commented out IPython magic to ensure Python compatibility.
# %ls -1 build/darknet/x64/data/obj/ | wc -l

import os, fnmatch
import numpy as np

train_file = open("build/darknet/x64/data/train.txt", "w")
valid_file = open("build/darknet/x64/data/valid.txt", "w")
listOfFiles = os.listdir('build/darknet/x64/data/obj/')  
pattern = "*.jpg"  
for f_name in listOfFiles:  
  if fnmatch.fnmatch(f_name, pattern):
    if np.random.rand(1) < 0.8:
      train_file.write("build/darknet/x64/data/obj/"+f_name+"\n")
      #print ("data/obj/"+f_name)
    else:
      valid_file.write("build/darknet/x64/data/obj/"+f_name+"\n")  
      
train_file.close()
valid_file.close()

#Count number of files 
!wc -l build/darknet/x64/data/train.txt
!wc -l build/darknet/x64/data/valid.txt

# Commented out IPython magic to ensure Python compatibility.
# %pycat build/darknet/x64/data/valid.txt

!wget -P build/darknet/x64/ https://pjreddie.com/media/files/darknet53.conv.74
#%ls build/darknet/x64/

